server:
  port: 8080
  
spring:
 profiles: local
 application:
   name: url-shortener-{spring.profiles.active}

mongodb: 
  db: terminology
  ip: localhost
  password: raja#1234
  port: 27017
  username: raja
     